### PR TITLE
Add, extractors for yinyuetai

### PR DESCRIPTION
**Pull request by lishubing**
Hi, it's me again.
As you may guess, I'm working on downloading MVs these days. 
So here is an extractor for 音悦台.

### CODE REVIEW

**Comment by lishubing** [comment]
Don't know why the build failed...
I'm able to access yinyuetai api from my home.
How about trying a rebuild?

**Comment by lishubing** [comment]
Maybe I should try to add https to api url...

**Comment by iawia002** [comment]
hey @lishubing, thanks for this, I'll take a look tonight

**Comment by lishubing** [comment]
Well...it seems that test build won't pass due to network issues, I gave up on it.
Yinyuetai cases already passed in the previous build, you may just continue to merge the code.

**Comment by iawia002** [comment]
OK then, I'll review the code tonight.

**Comment by iawia002** [comment]
Thanks! @lishubing

**Pull request merged**
