### PR TITLE
extractors: fix qq video, issue #723

### LINKED ISSUE #723: Can not download v.qq.com video. plz check ,thanks.
os: macOS 10.15.3

annie : 0.10.2

command : 
annie https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html

issue:

Downloading https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html error:
http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnCGdfJ6mqOYqku5Lz7Yyh2XQIczxI/c30731m13xg.m701.mp4?vkey=EBDA77EB676516F4CFDF86E6E0B89A0BDF6302C8359C3B8CF58C6FB572FDECA8B162B7D08D4B671AD560C49DDD2CF68E3975A9680806E45E1ED2549C395F596074CD1D5EF82804F87DD444CD76B05000201F3B4A97F66CA76C76C6613D49B3683B2CF00255B3F99F355E2A3BD64B8654 request error: HTTP 403

debug mode info:

 ~ annie -d "https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html"

annie: version 0.10.2, A fast, simple and clean video downloader.

URL:         http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=shd&vid=c30731m13xg
Method:      GET
Headers:     http.Header{
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
}
Status Code: 200

URL:         http://vv.video.qq.com/getkey?otype=json&platform=11&appver=3.2.19.333&filename=c30731m13xg.m701.mp4&format=100701&vid=c30731m13xg
Method:      GET
Headers:     http.Header{
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnCGdfJ6mqOYqku5Lz7Yyh2XQIczxI/"},
}
Status Code: 200
Downloading https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html error:
http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnCGdfJ6mqOYqku5Lz7Yyh2XQIczxI/c30731m13xg.m701.mp4?vkey=7F8B80F8497B64A2C5CB06B7159A8ED3E4F1CE09F281BB6B823AB1C2C3161AE262B08670D0EACA70A5956E2B90C561AC31B6929CCAA2DF72F362E0B9D4AD95B8116C4B8678896CD92D77D836F2349414F369ACF7A7625EF54B3CD48617972CC8DA171BF55B1F3BE09609AA3E969AB0C6 request error: HTTP 403

### PR DESCRIPTION
**Pull request by Half9000**
The old method of getting filename is invalid in some cases. 
Encapsulate the getting video information method into a function.
Fix #723

### CODE REVIEW

**Comment by iawia002** [comment]
Still getting an error:

```
Downloading https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html error:
http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnG2dfJ6kRFUoyvnY3GFatZbgKPNrS/shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4?vkey=DBAB96CB169EADA6DF44B12683B0257A40156D86D194FB20E271B7BF5B671AD47C96ED81D75254BA5D9A173D4A2D96BB8B6C5F5C7919BBD77904ACB1E5EA190C81EB124AB07F96F9B92A73FE23F705FECD6EEA6FC8A820B49D9D52D049AA892E34EA6F773B5BE9F665B0A959250065B9 request error: HTTP 404
```

**Comment by Half9000** [comment]
I am able to download the URL's video in Windows_64 and Linux_64.
There is part of the log output of this command:
`annie.exe -d https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html | tee vqq_patch.log`
[vqq_patch.log](https://github.com/iawia002/annie/files/4856077/vqq_patch.log)
Can you retry it with -d flag and attach the log file?

**Comment by iawia002** [comment]
That's strange, something wrong with my network?

```
$ annie -retry 1 -d https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html

annie: version 0.10.2, A fast, simple and clean video downloader.


URL:         http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=shd&vid=c30731m13xg
Method:      GET
Headers:     http.Header{
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "Referer":         {"https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html"},
}
Status Code: 200

URL:         http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=sd&vid=c30731m13xg
Method:      GET
Headers:     http.Header{
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Referer":         {"http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGlq2dfJ6kAKgAfQ4S6atHS0pozzmvG/"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
}
Status Code: 200

URL:         http://vv.video.qq.com/getkey?otype=json&platform=11&appver=3.2.19.333&filename=shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4&format=100701&vid=c30731m13xg
Method:      GET
Headers:     http.Header{
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGlq2dfJ6kAKgAfQ4S6atHS0pozzmvG/"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
}
Status Code: 200
Downloading https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html error:
http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGlq2dfJ6kAKgAfQ4S6atHS0pozzmvG/shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4?vkey=C3537CEF991E6673FACEFB5E353BBFB886D74298D5040F4E87E7AFC6DEA37C3BA7E7405BA639CC08AAEA967AB547BEC1F8A9AEFE5BDACA9CEDE06BC3F8FC1908829A46F2A2F23E06AEAE0AB3204CB479BCE00DBEC29D19B7530D68D6693E84B7B76226DFEE68EBDE661F4857A48AADD2 request error: HTTP 404
```

**Comment by Half9000** [comment]
That's odd. It might be caused by your network.
Here is screenshot of my request with aria2c:
image

**Comment by iawia002** [comment]
OK then, I'm gonna merge it.

**Comment by darkerlight007** [comment]
@Half9000 
Excuse me，I build it today,but it's also something wrong.

image

**Comment by Half9000** [comment]
> @Half9000
> Excuse me，I build it today,but it's also something wrong.
> 
> image

The issue is the 'Referer' header in the request for the vkey. I have fixed it in [here](https://github.com/Half9000/annie/tree/hotfix). If you are available, can you help me test it so I can open a new pull request?
Thanks in advance.

**Comment by darkerlight007** [comment]
> > @Half9000
> > Excuse me，I build it today,but it's also something wrong.
> > image
> 
> The issue is the 'Referer' header in the request for the vkey. I have fixed it in [here](https://github.com/Half9000/annie/tree/hotfix). If you are available, can you help me test it so I can open a new pull request?
> Thanks in advance.

It can work now,thanks!!!

**Comment by haroldyong** [comment]
> Still getting an error:
> 
> ```
> Downloading https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html error:
> http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnG2dfJ6kRFUoyvnY3GFatZbgKPNrS/shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4?vkey=DBAB96CB169EADA6DF44B12683B0257A40156D86D194FB20E271B7BF5B671AD47C96ED81D75254BA5D9A173D4A2D96BB8B6C5F5C7919BBD77904ACB1E5EA190C81EB124AB07F96F9B92A73FE23F705FECD6EEA6FC8A820B49D9D52D049AA892E34EA6F773B5BE9F665B0A959250065B9 request error: HTTP 404
> ```

I update the lastest code from master branch and go build it .  also still appear this error .

**Comment by haroldyong** [comment]
annie: version 0.10.3, A fast, simple and clean video downloader.


URL:         http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=shd&vid=c30731m13xg
Method:      GET
Headers:     http.Header{
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Referer":         {"https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html"},
}
Status Code: 200

URL:         http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=sd&vid=c30731m13xg
Method:      GET
Headers:     http.Header{
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnCGdfJ6mqOYqku5Lz7Yyh2XQIczxI/"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
}
Status Code: 200

URL:         http://vv.video.qq.com/getkey?otype=json&platform=11&appver=3.2.19.333&filename=shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4&format=100701&vid=c30731m13xg
Method:      GET
Headers:     http.Header{
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"http://vv.video.qq.com/getkey?otype=json&platform=11&appver=3.2.19.333&filename=shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4&format=100701&vid=c30731m13xg"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
}
Status Code: 200
Downloading https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html error:
http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnCGdfJ6mqOYqku5Lz7Yyh2XQIczxI/shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4?vkey=FE95A16AFA8E669680C434AF7E5F85F8BDD34CBCE9167D4D9B8B632E728D824FB0AF31ED47C60A2EFE1295CF18C29E03CA49C8FF8597FB23800C8CAFB29E3FA164F2FDEDB91688D2C0242CD5FB4C7D1DD654DB2D14EEA4A04201EF25A4668E33BF3B08701650BAFB47D4E43E4F56E97D request error: HTTP 404

**Comment by Half9000** [comment]
> > Still getting an error:
> > ```
> > Downloading https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html error:
> > http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnG2dfJ6kRFUoyvnY3GFatZbgKPNrS/shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4?vkey=DBAB96CB169EADA6DF44B12683B0257A40156D86D194FB20E271B7BF5B671AD47C96ED81D75254BA5D9A173D4A2D96BB8B6C5F5C7919BBD77904ACB1E5EA190C81EB124AB07F96F9B92A73FE23F705FECD6EEA6FC8A820B49D9D52D049AA892E34EA6F773B5BE9F665B0A959250065B9 request error: HTTP 404
> > ```
> 
> I update the lastest code from master branch and go build it . also still appear this error .

The CDN 'http://video.dispatch.tc.qq.com/' might be the factor to this problem. Sometimes, it will return HTTPSTATUS 404 while the program send request for the desired file. 
If there is no specific reason to use this CDN, maybe we can use the CDN with index 0. (extractors/qq.go ln: 210)
@iawia002

**Comment by iawia002** [comment]
> > > Still getting an error:
> > > ```
> > > Downloading https://v.qq.com/x/cover/mzc00200xa98807/c30731m13xg.html error:
> > > http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnG2dfJ6kRFUoyvnY3GFatZbgKPNrS/shg_24429200_50001_911dcb8061a6401f849d077b8b2f5bc3.f20211000.mp4?vkey=DBAB96CB169EADA6DF44B12683B0257A40156D86D194FB20E271B7BF5B671AD47C96ED81D75254BA5D9A173D4A2D96BB8B6C5F5C7919BBD77904ACB1E5EA190C81EB124AB07F96F9B92A73FE23F705FECD6EEA6FC8A820B49D9D52D049AA892E34EA6F773B5BE9F665B0A959250065B9 request error: HTTP 404
> > > ```
> > 
> > 
> > I update the lastest code from master branch and go build it . also still appear this error .
> 
> The CDN 'http://video.dispatch.tc.qq.com/' might be the factor to this problem. Sometimes, it will return HTTPSTATUS 404 while the program send request for the desired file.
> If there is no specific reason to use this CDN, maybe we can use the CDN with index 0. (extractors/qq.go ln: 210)
> @iawia002

SGTM, have a try!

**Pull request merged**
